### ISSUE TITLE
Databricks fresh start - p.run exception

### ISSUE THREAD

**Issue by paprocki-r** [mlflow/mlp-regression-template#53]
Hello! 
Running databricks notebook I am getting exception:

![image](https://user-images.githubusercontent.com/3410289/181239852-a4aa909f-f8bf-4cc3-ad0f-d48a79db5318.png)

**Comment by paprocki-r** [comment]
There is error that disappears quickly:

> 
> 2022/07/27 13:31:29 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
> 2022/07/27 13:31:29 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during spark autologging: Exception while attempting to initialize JVM-side state for Spark datasource autologging. Please create a new Spark session and ensure you have the mlflow-spark JAR attached to your Spark session as described in http://mlflow.org/docs/latest/tracking.html#automatic-logging-from-spark-experimental. Exception:
> An error occurred while calling z:org.mlflow.spark.autologging.MlflowAutologEventPublisher.register.
> : py4j.Py4JException: An exception was raised by the Python Proxy. Return Message: Traceback (most recent call last):
>   File "/databricks/spark/python/lib/py4j-0.10.9.1-src.zip/py4j/java_gateway.py", line 2442, in _call_proxy
>     return_value = getattr(self.pool[obj_id], method)(*params)
> AttributeError: 'PythonShell' object has no attribute 'replId'
> 
> 	at py4j.Protocol.getReturnValue(Protocol.java:476)
> 	at py4j.reflection.PythonProxyHandler.invoke(PythonProxyHandler.java:108)
> 	at com.sun.proxy.$Proxy84.replId(Unknown Source)
> 	at org.mlflow.spark.autologging.MlflowAutologEventPublisherImpl.register(MlflowAutologEventPublisher.scala:116)
> 	at org.mlflow.spark.autologging.MlflowAutologEventPublisherImpl.register$(MlflowAutologEventPublisher.scala:112)
> 	at org.mlflow.spark.autologging.MlflowAutologEventPublisher$.register(MlflowAutologEventPublisher.scala:20)
> 	at org.mlflow.spark.autologging.MlflowAutologEventPublisher.register(MlflowAutologEventPublisher.scala)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
> 	at py4j.Gateway.invoke(Gateway.java:295)
> 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at py4j.GatewayConnection.run(GatewayConnection.java:251)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> 2022/07/27 13:31:29 INFO mlflow._spark_autologging: Autologging successfully enabled for spark.
> 2022/07/27 13:31:29 INFO mlflow.tracking.fluent: Autologging successfully enabled for pyspark.
> 2022/07/27 13:31:29 INFO mlflow.tracking.fluent: Autologging successfully enabled for pyspark.ml.
